plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
    id 'jacoco'
    id 'org.jetbrains.kotlinx.kover' version '0.8.3'
    id 'io.gitlab.arturbosch.detekt' version '1.23.0'
}

android.buildFeatures.buildConfig true

android {
    namespace 'com.maxicruz.pokeapp'
    compileSdk 35

    defaultConfig {
        applicationId "com.maxicruz.pokeapp"
        minSdk 24
        targetSdk 35
        versionCode project.hasProperty('versionCode') ? project.versionCode.toInteger() : 1
        versionName "1.0"

        //testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file('release-key.jks')
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
        debug {
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
    }

    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.10"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
            all {
                testLogging {
                    jacoco {
                        includeNoLocationClasses = true
                        excludes = ['jdk.internal.*']
                    }
                }
            }
        }
    }
}

jacoco {
    toolVersion = "0.8.12"
}

tasks.withType(Test).configureEach {
    useJUnit()
    finalizedBy jacocoTestReport
    // Asegúrate de incluir las clases de los tests de Robolectric
    jacoco.includeNoLocationClasses = true
}

afterEvaluate {
    tasks.register("jacocoTestReport", JacocoReport) {
        dependsOn("testReleaseUnitTest")

        reports {
            xml.required.set(true)
            html.required.set(true)
        }

        sourceDirectories.setFrom(files("$projectDir/src/main/java"))
        classDirectories.setFrom(files("build/tmp/kotlin-classes/release"))
        executionData.setFrom(files("build/jacoco/testReleaseUnitTest.exec"))
    }
}

dependencies {
    // Jetpack Compose
    implementation "androidx.activity:activity-compose:1.8.2"
    implementation "androidx.compose.ui:ui:1.6.7"
    implementation "androidx.compose.material3:material3:1.2.1"
    implementation "androidx.compose.ui:ui-tooling-preview:1.6.7"
    debugImplementation "androidx.compose.ui:ui-tooling:1.6.7"
    implementation "androidx.compose.runtime:runtime-livedata:1.6.7"
    implementation "androidx.compose.foundation:foundation:1.6.7"
    implementation "androidx.compose.material:material:1.6.7"

    // Coil for image loading in Compose
    implementation "io.coil-kt:coil-compose:2.5.0"

    // Hilt for dependency injection
    implementation "com.google.dagger:hilt-android:2.51.1"
    kapt "com.google.dagger:hilt-android-compiler:2.51.1"
    implementation "androidx.hilt:hilt-navigation-compose:1.2.0"

    // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.7.0"

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    // Quitar ConstraintLayout
    // implementation libs.androidx.constraintlayout
    // Quitar RecyclerView
    // implementation libs.androidx.recyclerview

    // TypeSafe
    implementation libs.config
    // ViewModel
    implementation libs.androidx.lifecycle.viewmodel.ktx
    // LiveData
    implementation libs.androidx.lifecycle.livedata.ktx
    // Fragment
    implementation libs.androidx.fragment.ktx
    // Activity
    implementation libs.androidx.activity.ktx
    // Retrofit
    implementation libs.retrofit
    implementation libs.converter.gson
    // Corrutinas
    implementation libs.kotlinx.coroutines.android
    implementation libs.core.ktx
    testImplementation libs.kotlinx.coroutines.test
    // Dagger hilt
    implementation libs.hilt.android
    testImplementation libs.junit.jupiter
    kapt libs.hilt.compiler
    implementation libs.androidx.hilt.navigation.fragment

    // Quitar Glide
    // implementation libs.glide
    // Quitar kapt de Glide
    // kapt libs.compiler

    implementation libs.firebase.core

    testImplementation libs.junit
    testImplementation libs.mockk
    testImplementation libs.androidx.core.testing
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    // Dependencia de Robolectric
    testImplementation libs.robolectric
}
